labelPRBasedOnFilePath:
  🧠 area:core:
    - test/unit/core/**/*
    - src/core/**/*

  💻 area:dev:
    - .github/**/*
    - pyproject.toml

  📚 documentation:
    - docs/**/*
    - README.md

  🧪 area:matchers:
    - src/matchers/**/*

firstPRWelcomeComment: >
  🎉 Thanks for opening this pull request! Please check out our contributing guidelines.

firstPRMergeComment: >
  🎉 ⭐ ✨ Awesome work, congrats on your first merged pull request!

firstIssueWelcomeComment: >
  🎉 Thanks for opening your first issue here! Be sure to follow the issue template!
